spring.application.name=ApiGateway

server.port=9095

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# USER SERVICE ROUTE
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USERSERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**

# ORDER SERVICE ROUTE
spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ORDERSERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/orders/**

